#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget 
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/SturdyCat/Padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        #########################################################################################
        sed -i "/CONFIG_FIRMWARE_INCLUDE_QOS/d" .config
        echo "CONFIG_FIRMWARE_INCLUDE_QOS=y" .config

        sed -i "/CONFIG_FIRMWARE_INCLUDE_IFB/d" .config
        echo "CONFIG_FIRMWARE_INCLUDE_IFB=y" .config 

        sed -i "/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d" .config
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #科学上网插件

        sed -i "/CONFIG_FIRMWARE_INCLUDE_XRAY/d" .config
        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> .config #集成xray执行文件  ~4.5M

        sed -i "/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d" .config
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns

        sed -i "/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d" .config        
        sed -i "/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d" .config
        sed -i "/CONFIG_FIRMWARE_ENABLE_FUSE/d" .config        
        sed -i "/CONFIG_FIRMWARE_INCLUDE_AUDIO/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_UVC/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_ARIA/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_TROJAN/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_WYY/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_LPRD/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_FTPD/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_SMBD36/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_SMBD/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_SOCAT/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_SRELAY/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_MTR/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_TTYD/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d" .config
        sed -i "/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d" .config

        cp -f .config configs/templates/$TNAME.config 
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
